### ISSUE TITLE
Add Syntax for memory(ram) read/write like x86 assembly and addition of pointers

### ISSUE THREAD

**Issue by furesoft** [eugenelepekhin/Fusion#1]
like:
`
lea eax, [edx + ebx]
`

and have some function that can check if its an memory operation:
`
macro lea dst, src {
     if(isMemory(src)) {
          0x8D | dst << 16 | src 
     }
}
`

**Comment by eugenelepekhin** [comment]
Can you elaborate in this a bit more? What is the difference between this syntax and any other expression? May be some more examples..

**Comment by furesoft** [comment]
this syntax indicates that the data comes directly from the memory. another example would be:

lea eax, QWORD PTR [ebx]

that would dereference the value that is at address stored in ebx.


the memory and pointer features would be really useful to distinguish and make beautiful assembly instructions instead of implementing for every kind of instruction a new mnemnonic

**Comment by eugenelepekhin** [comment]
If you have an expression: [a + b] how are you going to distinguish if "a" a register or other memory expression?

**Comment by furesoft** [comment]
maybe by defining  a as register? idk

**Comment by eugenelepekhin** [comment]
In x86 assembler the expression [ax + 42] means add value in ax add 42 to it and use the result as an address.
Alternatively, you can write [ax + bx] meaning take value in ax add value in bx and use the result as an address.
In Fusion this will be just an expression which will calculated to a number. So, if you have a register "a" that you defined as: macro a {2} and later you try to write the analog of the above expression: [a + 42] the result will be 44. It will not help you inside the macro. I guess you will need to define multiple macros with different parameters to simulate the x86 behavior in Fusion.
For example macro addm targetReg, indexReg, offset {...} versus to macro addr targetReg, sourceReg {...}

**Comment by eugenelepekhin** [comment]
I probably know what to do here. Will try to implement it.

**Comment by eugenelepekhin** [comment]
This should be fixed now.
